## 使用 github action 打包最新的 burp 插件

### 前言

大部分的 burp 插件都是基于 JAVA 开发的，我们可以使用 github 的 action 打包插件最新版

### maven 项目的 jar 打包

```yaml

name: maven build and push

# author Mrxn
# github: github.com/Mr-xn

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: 
        mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: # optional, default is artifact
          burpplug
        # A file, directory or wildcard pattern that describes what to upload
        path: 
          target/*.jar
        # The desired behavior if no files are found using the provided path.
